name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code (recursive)
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
        
