name: pull-request-audit

on:
  push:
    branches: [ main ]
  
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: ros-tooling/setup-ros@v0.2
      with:
        required-ros-distributions: noetic
        


        
